name: Deploy React to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: bitovi/github-actions-react-to-ghp@v1.2.0
      with:
      # Specifies if this action should checkout the code
      checkout: true # optional, default is true

      # Specifies the path of the static assets after building
      path: dist # optional, default is dist

      # Specifies the command to run after npm ci for the build
      build_command: npm run build # optional, default is npm run build
